### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by AngusMenter** [AllenDowney/ElementsOfDataScience#1]
02_times.ipynb text after cell 13:

You can also get[s] the name of the month and the day of the week.

**Comment by AngusMenter** [comment]
also "So haversin[] is a variable that refers to a function."

let me know if typos will get picked up anyway and i won't note them

**Comment by AllenDowney** [comment]
I will fix those.  And yes, this is helpful.  Thanks!

**Comment by AngusMenter** [comment]
ok. what a great resource, thank you.

04_loops, Whitespace section:

If we run the loop again and display the final value of line, we see that there [is] are two extra characters at the end:

**Comment by AngusMenter** [comment]
05_dictionaries, text after cell 41:

It looks like there are about [than] 42,000 different words

**Comment by AngusMenter** [comment]
hi Allen do you also want more general (concise) feedback? keen to help but only if useful

**Comment by AllenDowney** [comment]
I am always happy to get suggestions (with the understanding that I will not always take them :)

**Comment by AngusMenter** [comment]
haha, of course!

in chap 03 it took me a while to work out / remember that 1/N Sigma is 1/count*sum aka mean. thought a note that that's what it means might be user friendly

**Comment by AngusMenter** [comment]
06_plotting

text under cell 39 reads like the solution is provided rather than created by the user: 'And here's a solution to one of the previous exercises. It loops through..'

**Comment by flothesof** [comment]
Hi Allen, I catched some typos and thought it would be okay to post them here (even though it makes the issue a bit messy...):

### 02_times.ipynb
- Pandas provides type called Timestamp, which represents a date and time. --> missing "a"
- Positive longitude for the eastern hemisphere and negative **latitude** for the western hemisphere. --> should be **longitude**

Thanks for putting together this project!

**Comment by AngusMenter** [comment]
chap 07, intro:

So, han[d] in there!

**Comment by AllenDowney** [comment]
I will fix those and push changes soon. Thank you!

**Comment by AngusMenter** [comment]
chap 07, cell 169 Exercise; steps 4 & 5 already have the code in subsequent cell

**Comment by AllenDowney** [comment]
Fixed!

**Comment by AngusMenter** [comment]
chap 08: Goals; not sure if CDF is intentionally written long hand as mass function; elsewhere it is written as distribution function

**Comment by AngusMenter** [comment]
chap 08, text under cell 6:

To import it, I'll use a version of the import statement we have [note] seen before.

**Comment by AngusMenter** [comment]
chap 08, text under cell 50 (exercise to plot CDFs of high,assc & bach incomes)

solution is provided

**Comment by AngusMenter** [comment]
chap 09, text under cell 88:

explanatiion written as commented code rather than text

**Comment by AllenDowney** [comment]
chap 09, text under cell 88:  I can't find this one.  The cell numbers depend on your order of evaluation.  Can you give me some text to search for?

**Comment by mohamed-a** [comment]
notebook 1 underneath cell 26 - typo (garbled text)

4 exampel in Ingli\$h you kin get prackicly evRiThing rong-rong-rong and sti11 be undr3stud.

**Comment by wybeturing** [comment]
Hi @mohamed-a, that is not actually a typo. The inclusion is intended to show that in natural languages like English, we can get practically everything wrong and still be understood. Not so with formal languages like Mathematics or Logic. The apparent typo is there for demonstration purposes. I hope this is right @AllenDowney.

**Comment by mohamed-a** [comment]
notebook1 text in compound interest section:
Dollar sign $ shows as \\$ (escaped character)

**Comment by AllenDowney** [comment]
@mohamed-a Thanks, will fix.

**Comment by mohamed-a** [comment]
notebook 2 Location cell second bullet:

- Positive longitude for the eastern hemisphere and negative **latitude** _longitude_ for the western hemisphere.

**Comment by mohamed-a** [comment]
I meant replace latitude with longitude

**Comment by miwojc** [comment]
Notebook 05_dictionaries.ipynb
typo in Punctuation chapter?
it says: "It words pretty well..."
should be: "It works pretty well..." ?

**Comment by AllenDowney** [comment]
Thank you all for these! Sorry it took me so long to fix them, but I think I am caught up now.
