### ISSUE TITLE
Consider editing the footer to show the public license on the online content

### ISSUE THREAD

**Issue by labarba** [AllenDowney/ElementsOfDataScience#12]
The JupyterBook footer has the standard copyright notice, with:

> By Allen B. Downey
> © Copyright 2023.

On the repository, we find a LICENSE file showing MIT license. I guess I have two points to make: should you have a double license situation here, MIT for code and CC-BY for content? Second is to suggest modifying the footer to show the license.

**Comment by AllenDowney** [comment]
@labarba Thanks for letting know know about these issues. I'll get them squared away next time I build the book.

**Comment by AllenDowney** [comment]
Done!
