### ISSUE TITLE
02_times: import error for utils.wrap

### ISSUE THREAD

**Issue by misken** [AllenDowney/ElementsOfDataScience#13]
The line `from utils import wrap` leads to an `ImportError`. It doesn't appear that the `wrap()` function is in `utils.py`.

**Comment by AllenDowney** [comment]
I'll check it out as soon as I can. What environment are you running the notebook in?

**Comment by misken** [comment]
Local Jupyter Lab.

**Comment by AllenDowney** [comment]
It looks like the released version of `utils.py` was out of sync. Should be fixed now -- if you delete your local copy and run the notebook again, it should download the correct one.

Also, you might have to `pip install geodatasets` when you get to it. Let me know how it goes!
