### ISSUE TITLE
notebook 13 down

### ISSUE THREAD

**Issue by daniel-saunders-phil** [AllenDowney/ElementsOfDataScience#3]
The link to run notebook 13 on collab and the one to download it both return 404 errors. I also noticed there are two notebook 11s in the repository, one for inference and the other for resampling. Perhaps the inference notebook got mislabeled?

**Comment by AllenDowney** [comment]
Those should be working now.  Thanks for letting me know!

There are two notebook 11s because the old 11_inference has been replaced with the new chapters 11, 12, and 13. I'm leaving the old one in place for one more revision.
