### ISSUE TITLE
01_variables: Small typo

### ISSUE THREAD

**Issue by jfkoh** [AllenDowney/ElementsOfDataScience#9]
Hi Allen,

In 01_variables, I noticed a grammar typo in the first sentence of the first section. There's an extra "s" which shouldn't be there:

"Data science is the use of data to answer**s** questions and guide decision making."

I'm a big fan of Thinking Python and want to take this opportunity to thank you for writing all your wonderful books and releasing them under Creative Commons :)

JF Koh from Singapore

**Comment by AllenDowney** [comment]
Thanks for letting me know about the error, and thanks for your kind words.

**Comment by AllenDowney** [comment]
Fixed (finally)! The change will propagate soon.
